name: Check Blocked PR Comments

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR comments
        id: get-comments
        uses: actions/github-script@v7
        with:
          script: |
            // Get inline review comments
            const { data: reviewComments } = await github.rest.pulls.listReviewComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            let blockedComments = [];
            
            // Only add comments that:
            // 1. Contain [BLOCKED]
            // 2. Are not marked as resolved in GitHub
            blockedComments.push(...reviewComments.filter(comment => 
              comment.body.includes('[BLOCKED]') && !comment.resolved
            ));
            
            if (blockedComments.length > 0) {
              core.setFailed(`Found ${blockedComments.length} unresolved [BLOCKED] comments. Please resolve them before merging.`);
              
              console.log('Blocked Comments:');
              blockedComments.forEach(comment => {
                console.log(`- ${comment.html_url}`);
                console.log(`  ${comment.body}`);
                if (comment.path && comment.line) {
                  console.log(`  File: ${comment.path}, Line: ${comment.line}\n`);
                } else {
                  console.log('\n');
                }
                console.log(`resolved status  ${comment.resolved}`);
              });
            } else {
              console.log('No unresolved [BLOCKED] comments found.');
            }