name: Always Fail Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  fail-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a failure message
        run: |
          echo "This workflow is designed to fail."
      
      - name: Set the workflow status to failed
        run: |
          echo "Failing the job intentionally."
          exit 1  # Forces the step to fail
