name: Check Blocked PR Comments

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  check-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR comments
        id: get-comments
        uses: actions/github-script@v7
        with:
          script: |
            // Get review threads which include resolution status
            const { data: threads } = await github.rest.pulls.listReviewThreads({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            let blockedComments = [];
            
            // Debug logging
            console.log('Checking review threads for [BLOCKED] status:');
            threads.forEach(thread => {
              console.log(`Thread resolution status: ${thread.isResolved}`);
              thread.comments.forEach(comment => {
                console.log(`Comment: ${comment.body.substring(0, 50)}...`);
              });
            });
            
            // Check each thread
            threads.forEach(thread => {
              // If any comment in the thread contains [BLOCKED] and the thread isn't resolved
              if (!thread.isResolved && thread.comments.some(comment => comment.body.includes('[BLOCKED]'))) {
                blockedComments.push(...thread.comments.filter(comment => 
                  comment.body.includes('[BLOCKED]')
                ));
              }
            });
            
            if (blockedComments.length > 0) {
              core.setFailed(`Found ${blockedComments.length} unresolved [BLOCKED] comments. Please resolve them before merging.`);
              
              console.log('Blocked Comments:');
              blockedComments.forEach(comment => {
                console.log(`- ${comment.html_url}`);
                console.log(`  ${comment.body}`);
                if (comment.path && comment.line) {
                  console.log(`  File: ${comment.path}, Line: ${comment.line}\n`);
                } else {
                  console.log('\n');
                }
              });
            } else {
              console.log('No unresolved [BLOCKED] comments found.');
            }