name: PR Title Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    runs-on: ubuntu-latest

    steps:
    - name: Validate PR title
      uses: actions/github-script@v6
      with:
        script: |
          const prTitle = context.payload.pull_request.title.trim();
          console.log(`PR Title: "${prTitle}"`);
          
          // Updated regex to allow numbers in the first 8 characters
          const regex = /^[a-zA-Z0-9]{8}: .+/;
          
          if (!regex.test(prTitle)) {
            throw new Error(`Invalid PR title: "${prTitle}". It must start with exactly 8 alphanumeric characters (letters or numbers), followed by ": " and at least one more character.`);
          }
          console.log('PR title is valid.');
