name: PR Title Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr-title:
    runs-on: ubuntu-latest

    steps:
    - name: Debug PR title
      uses: actions/github-script@v6
      with:
        script: |
          const prTitle = context.payload.pull_request.title;
          console.log(`PR Title: "${prTitle}"`);
          const regex = /^[a-zA-Z]{8}: .+/;
          if (regex.test(prTitle)) {
            console.log('PR title is valid.');
          } else {
            console.log('PR title is invalid.');
          }
    - name: Validate PR title
      uses: actions/github-script@v6
      with:
        script: |
          const prTitle = context.payload.pull_request.title;
          const regex = /^[a-zA-Z]{8}: .+/;
          if (!regex.test(prTitle)) {
            throw new Error(`Invalid PR title: "${prTitle}". It must start with exactly 8 letters, followed by ": " and at least one more character.`);
          }
